[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=63072000; includeSubDomains"
Content-Security-Policy = "default-src 'https:';base-uri 'none';frame-ancestors 'none'"
Referrer-Policy = "strict-origin"
